### PR TITLE
Migrate from Maven to Gradle Kotlin Build

### PR DESCRIPTION
**Pull request by GeorgeV220**
#### Overview

This PR introduces significant changes to the project build system by switching from Maven to a Gradle Kotlin build. It also includes the conversion of several Java files to Kotlin, specifically targeting interfaces and enums.

#### Changes

- **Build System Migration**: 
  - Switched from Maven to Gradle Kotlin DSL.
  - Configured the Gradle build to function correctly and efficiently.

- **Code Conversion**:
  - Converted specific `.java` files to `.kt` files

#### Additional Notes

- The commit history includes some questionable commits, it's advisable to squash them for a cleaner history before merging.
- The new Gradle build has been tested and works as intended. 
- JitPack has successfully built and uploaded the project with the new configuration. 
  - [JitPack Build Status](https://jitpack.io/#GeorgeV220/holoeasy/0fdf7a545f)
  - [Build Log](https://jitpack.io/com/github/GeorgeV220/holoeasy/0fdf7a545f/build.log)

### CODE REVIEW

**Comment by unldenis** [comment]
LGTM, as soon as I can I would gladly make you a small donation for your effort, since almost a year has passed since we talked about Gradle.

**Comment by unldenis** [comment]
@GeorgeV220 look like there is a problem in the github action https://github.com/unldenis/holoeasy/actions/runs/11653705231/job/32446380120

**Comment by unldenis** [comment]
@GeorgeV220 sorry again, but i think you can try too, if you clone the repo and try to load gradle configurations with intellij it will give you an error or stuck at building model.

**Comment by GeorgeV220** [comment]
> @GeorgeV220 for the two plugin examples, how can I include the dependencies in the jar build? I tried the shadowJar plugin but for some reason with this configuration the jar is 91MB, it includes groovy? and gradle files?

If you can please let's continue this discussion at discord or in the discussions page. My discord username is `georgev22`

**Pull request merged**
